{% set name = "dask-cuda" %}
{% set version = "0.19.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-cuda-{{ version }}.tar.gz
  sha256: 891a142ed001ec8ab2f5775fc7bd1e992c226273078bdddebad8a1111562b92f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-cuda-worker = dask_cuda.cli.dask_cuda_worker:go

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dask >=2.9.0
    - distributed >=2.18.0
    - numba >=0.50.0,!=0.51.0
    - numpy >=1.16.0
    - pynvml >=8.0.3

test:
  imports:
    - dask_cuda
    - dask_cuda.benchmarks
  commands:
    - pip check
    - dask-cuda-worker --help
  requires:
    - pip

about:
  home: https://github.com/rapidsai/dask-cuda
  summary: Utilities for Dask and CUDA interactions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
