{% set name = "dask-cuda" %}
{% set version = "21.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask-cuda-{{ version }}.tar.gz
  sha256: bc9b028e5bbb9cefb77e55a6caa9ac5cf6ec049d5221f75219ddfd0d8b184a7f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-cuda-worker = dask_cuda.cli.dask_cuda_worker:go

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dask >=2.22.0,<=2021.5.1
    - distributed >=2.22.0,<=2021.5.1
    - numba >=0.53.1
    - numpy >=1.16.0
    - pynvml >=8.0.3

test:
  imports:
    - dask_cuda
    - dask_cuda.benchmarks
  commands:
    - pip check
    - dask-cuda-worker --help
  requires:
    - pip

about:
  home: https://github.com/rapidsai/dask-cuda
  summary: Utilities for Dask and CUDA interactions
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - jakirkham
